---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html  # Update this path
    - /bin/cp -R * $DEPLOYPATH  # Copies all project files
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader  # Installs PHP dependencies
    - php artisan migrate --force  # Runs database migrations
    - php artisan config:cache  # Caches configuration
    - php artisan route:cache  # Caches routes
    - php artisan view:cache  # Caches views
    - php artisan storage:link  # Creates symbolic link for storage folder
